sonar.projectKey=payments-ms
sonar.projectName=payments-ms
sonar.projectVersion=0.0.1
sonar.sourceEncoding=UTF-8

# Fuentes
sonar.sources=src
sonar.tests=test

sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/coverage/**,\
  **/coverage-e2e/**,\
  src/main.ts

sonar.test.inclusions=\
  test/**/*.e2e-spec.ts,\
  test/**/*.integration-spec.ts

# Cobertura
# Generada por: npm run test:e2e:cov
sonar.javascript.lcov.reportPaths=coverage-e2e/lcov.info

# TypeScript
sonar.typescript.tsconfigPath=tsconfig.json

# Servidor SonarQube
sonar.host.url=http://localhost:9000
sonar.token=sqa_0b168c76c160862f751fa1fca18740577a81cf8e
