# Identificación del proyecto
sonar.projectKey=orders-ms
sonar.projectName=Orders Microservice
sonar.projectVersion=0.0.1
sonar.sourceEncoding=UTF-8

# Fuentes
sonar.sources=src
sonar.tests=test

# Excluye archivos que no aportan cobertura significativa
sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/coverage/**,\
  **/coverage-e2e/**,\
  src/main.ts

sonar.test.inclusions=\
  test/**/*.e2e-spec.ts,\
  test/**/*.integration-spec.ts

# Cobertura
sonar.javascript.lcov.reportPaths=coverage-e2e/lcov.info

# TypeScript
sonar.typescript.tsconfigPath=tsconfig.json

# Servidor SonarQube
# Sobreescribir con SONAR_HOST_URL y SONAR_TOKEN al ejecutar sonar-scanner
sonar.host.url=http://localhost:9000
sonar.token=sqa_5608b71d1fd06d14d305db263b104cbb9667d853